// Code generated by "spawner "; DO NOT EDIT.

package msg

type factory func() interface{}

func Spawner(name string, newPool ...bool) (interface{}, bool) {
	f, ok := spawner[name]
	if !ok {
		return nil, ok
	}
	return f(), true
}

var spawner = map[string]factory{
	"msg.Pong":              func() interface{} { return &Pong{} },
	"msg.LoginReq":          func() interface{} { return &LoginReq{} },
	"msg.LoginResp":         func() interface{} { return &LoginResp{} },
	"msg.Ping":              func() interface{} { return &Ping{} },
	"msg.ChatReq":           func() interface{} { return &ChatReq{} },
	"msg.ChatResp":          func() interface{} { return &ChatResp{} },
	"msg.BroadcastMsg":      func() interface{} { return &BroadcastMsg{} },
	"msg.ChatMsg":           func() interface{} { return &ChatMsg{} },
	"msg.SessionBroken":     func() interface{} { return &SessionBroken{} },
	"msg.GateMsgWrapper":    func() interface{} { return &GateMsgWrapper{} },
	"msg.UserEnterRoomReq":  func() interface{} { return &UserEnterRoomReq{} },
	"msg.UserEnterRoomResp": func() interface{} { return &UserEnterRoomResp{} },
}

func Put(name string, x interface{}) {}
